### ISSUE TITLE
There doesnt seem to be a way to remove authorized client from vault_keys

### ISSUE THREAD

**Issue by vinyar** [chef/chef-vault#103]
Hi, I was unable to find a way to remove clients from vault_keys. Maybe I'm just missing something simple, but here is the full writeup in case it's a bug/regression.

Use case:
I have around 50 active test nodes, and vault_keys has almost 400 entries from the various nodes created and deleted over the last couple of months. In an auto scaling environment where nodes are brought up and down continuously, the vault_keys will quickly become unwieldy. We would like to make chef-vault client removal part of automated server decommission.

Knife vault update command updates existing clients, but does not remove clients excluded from the search:
example:

```
knife vault update alexv alexvault \
'{"vaultuser":"$6$VqEIDjsp$7NtPMhA9cnxvSMTE9l7DMmydJJEymi9b4t1Vhk475vrWlfxMgVb3bDLhpk/RZt0J3X7l5H8WnqFgvq3dIa9Kt/"}' \
 --search 'recipe:test_recipe NOT name:server3' \ 
 --admins alex --mode client
```

result:

```
knife data bag show alexv alexvault_keys

  server1
  server2
  server3
  server4
id:                 alexvault_keys
search_query:                 recipe:ge_role_secure_os NOT name:server3
```

I've tested various methods, and the only way that worked for me, was to delete the vault_keys item with (knife data bag delete alexv alexvault_keys) and recreate it with the knife vault create query above. A very heavy handed approach.

working solution:

```
knife data bag delete alexv alexvault_keys
knife vault create alexv alexvault '{"vaultuser":"$6$VqEIDjsp$7NtPMhA9cnxvSMTE9l7DMmydJJEymi9b4t1Vhk475vrWlfxMgVb3bDLhpk/RZt0J3X7l5H8WnqFgvq3dIa9Kt/"}' --search 'recipe:test_recipe NOT name:server3' --admins alex --mode client
```

```
knife data bag show alexv alexvault_keys

  server1
  server2
  server4
id:                 alexvault_keys
search_query:                 recipe:ge_role_secure_os NOT name:server3
```

Solution:
There should be a command to remove authorized clients without having to delete the data_bag which can be ran as part of server removal automation. I'm fairly new to chef-vault, so if update switch used to perform this function, would it be possible to reimplement it?

**Comment by 8la** [comment]
This behaviour and the --clear switch should be documented at the README please!

Thanks!

**Comment by vinyar** [comment]
:+1: :coffee: for the --clean switch
