### ISSUE TITLE
Create, Refresh and Update behaviours

### ISSUE THREAD

**Issue by galindro** [chef/chef-vault#118]
I need to understand Create, Refresh and Update behaviours. This is my scenario:

I need to create a vault named customer_vault and an item called aws. It executed this command to create it:

```
knife vault create customer_vault aws --mode client --search "roles:AWS_Api" --admins "admin"
```

This means that chef-vault will search for all nodes that have the AWS_Api role directly associated to it or indirectly (nested from other role). After executed that, I've noticed that Chef Vault doesn't found any Nodes. But, if I change the search from "roles:AWS_Api" to "role:AWS_Api" and directly associate that role to a node, chef-vault could found the node and add it to the item aws inside customer_vault data bag.

Now I want to know what I'm need to do in the following situations:
1. How can I make a search that found nodes that inherits a role from other role?
2. If I want to add a node to that vault, what is the correct procedure?
3. If I want to delete a node to that vault, what is the correct procedure?
4. If I want to delete a node that is already deleted from Chef, what is the correct procedure?

**Comment by shinitiandrei** [comment]
Hi guys! Just wondering here then....regarding the first comment, @galindro mentions that chef vault basically **does not support nested roles**, which is what my team really rely on.
So my question would be, is there any forecast to s**upport nested roles** or that will not be supported at all? 
If not supported, what would be a workaround? Just adding each role with nodes that we have to the -S parameter?

Thanks heaps!!
