### ISSUE TITLE
Chef 12.4.0 breaks user patch

### ISSUE THREAD

**Issue by blacksails** [chef/chef-vault#176]
The changes in Chef::User breaks https://github.com/Nordstrom/chef-vault/blob/master/lib/chef-vault/chef_patch/user.rb because the method name no longer exists on Chef::User

**Comment by blacksails** [comment]
It seems that the chef team is working on a fix https://github.com/chef/chef/issues/3628

**Comment by btm** [comment]
fixed in https://github.com/chef/chef/pull/3630 and released in 12.5.1+
