### ISSUE TITLE
Refresh fails if no search expression is set

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-vault#188]
```
knife vault create cd test
knife vault refresh cd test
```
Leads to:
```
ERROR: The data in your request was invalid
Response: invalid search query: '[]'
```
Verbose output:
```
<snip>
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 400 Bad Request: error
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!': 400 "Bad Request" (Net::HTTPServerException)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:146:in `request'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/rest.rb:120:in `get'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/search/query.rb:158:in `call_rest_service'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/search/query.rb:87:in `search'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.6.1/lib/chef-vault/item.rb:80:in `clients'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.6.1/lib/chef-vault/item.rb:353:in `refresh'
<snip>
```
Adding some arbitrary search that will not match anything (e.g. `-S chef_environment:none`) is a workaround.

**Comment by thommay** [comment]
I'm not really clear what the use case for not including a search is; are you pre-creating a vault with the intention of adding new nodes to it later?

**Comment by christinedraper** [comment]
I'm provisioning nodes using CloudFormation and a shared validator key.  The nodes need to bootstrap and be able to access the vault, which they do by specifying the shared validator client/key.  

When I encountered the above, I had added the shared validator client/key to the vault as if it were an admin user.  I have subsequently changed to creating a node corresponding to that shared validator, and using a search expression for that node to associate the client/key with the vault. That avoids the above problem but eats into my node limit, particularly as I would like to create multiple different validator keys for different environments.

**Comment by thommay** [comment]
Hmm. Having just tried that I can't reproduce it (with current master). 
```
15:09 ~/work/test % knife vault create credentials database2 -J ./database.json

15:10 ~/work/test % knife vault update credentials database2
15:10 ~/work/test %
```
the _keys item is:
```
15:10 ~/work/chef-vault % knife data bag show -fj credentials database2_keys
Unencrypted data bag detected, ignoring any provided secret options.
{
  "id": "database2_keys",
  "admins": [
    "thom"
  ],
  "clients": [

  ],
  "search_query": [

  ],
  "thom": "nxp7tsDPaVUH4a9NDdNv90gs4sxbGUB5EWmhMO04bjHP7wGBgriGAn+g0UAs\nOUvy3nEmHRMwdcKf8h4WZK/6/w2n+bHeawA2zA4rU80zVtq6cSoT+Z3plBvG\n3ElxLkXwqxDTUJSTvtpSz/lGtmEYVW/+v4DoMfWHO3r5gTtQahZr9l7NbXE3\nnsqRCo2hti+h1JkZQ3pNRVow15u9+D9jkGr66/Qu1AlzNqBvngwVr/YNeR1r\n2el0TFgK5C8VX4GbliRz7cs+hy6VUzoes5Hfyu4UhHmZdW2GMa/M7rTeHL9y\nDUmzpvwy6/nI5DMfC25j0b7qkJAdAU2yv4l5oKgJLQ==\n"
}
```

**Comment by christinedraper** [comment]
Try 'refresh' on your example. My use case for needing to refresh was changing the validator key.

**Comment by thommay** [comment]
oh, sorry! Right, I'll take a look at this now.

**Comment by thommay** [comment]
Hm, so looking further I don't think I'm going to fix this specific bug. It seems more appropriate for you to use `knife vault rotate keys cd test` (or `knife vault rotate all keys`) to forcibly reencrypt everything, which doesn't require a search and is designed to handle admins as well as clients. Refresh is really just going to work on clients, it won't touch admins that I can see.

Does that make sense?

**Comment by christinedraper** [comment]
You're right, that makes more sense.
