### ISSUE TITLE
add user key to vault 

### ISSUE THREAD

**Issue by pjohnson-ptc** [chef/chef-vault#199]
Can the documentation be updated to show a clear example of how to "update" a vault to add a existing user to the keys file for a encrypted vault?  This is not extremely clear at all.

If a vault is created by user-1 can't user-2 be added to the vault to avoid this error:
[2016-02-08T14:55:20-08:00] FATAL: ChefVault::Exceptions::SecretDecryption: integration/passwords is not encrypted with
your public key.  Contact an administrator of the vault item to encrypt for you!

I realize this can be avoided by adding the "search tag" to the node and then having the original vault creator run the "vault refresh", but ideally we would not have to do this on a per-node basis.

**Comment by thommay** [comment]
I'm not super clear what you're asking here. The model of chef-vault is that an admin chooses the set of nodes and users to encrypt the data bag item for. If you're not in that original set, then only someone who is in that set can add you, because it's reliant on being able to read the shared secret - which is only available to people in the original list.

**Comment by pjohnson-ptc** [comment]
I think it's not entirely clear how to allow new "users" (vs nodes)

 knife vault update myvault datasafe -S 'tags:BitBucket' -M client
(and then refresh to update the vault with latest "Bitbucket" server)
But how to add a new user to the vault?

**Comment by pburkholder** [comment]
From https://www.chef.io/blog/2016/01/21/chef-vault-what-is-it-and-what-can-it-do-for-you/...

> Adding a new Admin User
> If you need to add a new admin user, run knife vault update with the vault name, the encrypted item within the vault, and -A flag, and the user’s username on the Chef Server.
```
$ knife vault update credentials database -A “new-username”
```

need the `-M client` option too.

**Comment by pjohnson-ptc** [comment]
@pburkholder  - thanks.  This is what was not so clear.  Much appreciated.

**Comment by timea** [comment]
This is really not clear, as adding the -M option is not in the[ knife examples.](https://github.com/chef/chef-vault/blob/master/KNIFE_EXAMPLES.md)

I have only found it here browsing the issues. Can you please update it from 

knife vault update passwords root -A "admin1,admin2"

to 

knife vault update passwords root -A "admin1,admin2" -M client
?

And why do we need the -M client option?

Thanks in advance!

**Comment by pburkholder** [comment]
Hi Timea,

In the README.md, under `global options` the first option is: `--mode MODE` where the default is `solo` which is primarily useful only for testing.

For any useful chef-vault operations you need to interact with the ChefServer, as a client, so you need `--mode client`.

I think the https://github.com/chef/chef-vault/blob/master/KNIFE_EXAMPLES.md are misleading, so I think a pull request that added `-M client` to the examples would be useful.

Good luck, Peter
