### ISSUE TITLE
Vault with item named "*_keys" is not recognised

### ISSUE THREAD

**Issue by rveznaver** [chef/chef-vault#205]
If a vault contains an item whose name ends with "_keys" it will not be recognised as a vault and will therefore not appear when listing vaults with knife.

**Comment by kamaradclimber** [comment]
Very likely due to https://github.com/chef/chef-vault/blob/6cc0b5f72784076ba389a5848dd23cbe1a01b716/lib/chef/knife/vault_base.rb#L56

**Comment by thommay** [comment]
I think the only sensible thing we can do here is to document that you will run into all sorts of sadness if you do this, due to the way the keys related to the data bag are saved.

**Comment by rveznaver** [comment]
I think this issue is only related to the way knife checks if something is a vault or not. I will dig more into it when I find some time.

**Comment by thommay** [comment]
well. yes and no; when you create a vault item called `foo`, vault also creates a data bag item called `foo_keys`, to store the keys in. So while yes, you can create an item called `foo_keys` and vault will happily then create `foo_keys_keys` to store the keys in, there's no way for it to then know that `foo_keys` isn't a hanging set of keys for an item called `foo`.
