### ISSUE TITLE
Issues with Simplest Chef Zero Use Case - No keys defined or No Implicit Conversion

### ISSUE THREAD

**Issue by rpattcorner** [chef/chef-vault#210]
Am trying to create a very simple use case where vault manages some secrets on a server-less chef-local/chef-zero installation

I have similar issues to [this post link](https://github.com/chef/chef-vault/issues/183) and would appreciate help understanding what I'm missing, probably in creating admins.

As background, we're striving for simplicity, so there is no /home/username/.chef directory and chef local works exclusively in a simple directory that chef zero/local treats as a repository path, containing a cookbooks subdirectory, a roles subdirectory, etc.

We start with the simplest possible command: 
`sudo knife vault create passwords root '{"username": "root", "password": "mypassword"}' -z`

which yields 

WARNING: No knife configuration file found
ERROR: ChefVault::Exceptions::NoKeysDefined: No keys defined for root

and from reading the prior post it sounds like we need to declare administrators with associated public keys in the chef-zero installation so that Vault has something to encrypt with.  Makes sense, but not much doc on how to create these admins, so I've made a try and:
- Created a clients directory in the current chef repository path 
- Created an admin.json file in the clients directory, with a valid public key
- Created a knife.rb file in the current path that references the admin, like this:

`chef_zero.enabled = true
knife[:vault_admins] = ['admin']`

So the directory we run from winds up looking like this:
```$ ls
cookbooks  data_bags  environments  knife.rb  roles clients

and reference the admin running the command like:

`sudo knife vault create passwords root '{"username": "root", "password": "mypassword"}' -z -A admin`

but I get:

ERROR: TypeError: no implicit conversion of String into Integer

Could someone tell me the simplest possible setup for chef-zero that would allow for use of vault to encrypt and decrypt some simple secrets?

**Comment by rpattcorner** [comment]
The following -VV display could be germane ... need a way perhaps to specify the encryption key in the zero environment.  Just adding -k <path to pem file> doesn't help

```
DEBUG: #<ChefZero::RestRequest:0x00000001e1d358 @env={"SCRIPT_NAME"=>"", "SERVER_NAME"=>"localhost", "REQUEST_METHOD"=>"GET", "PATH_INFO"=>"/data/passwords/root_keys", "QUERY_STRING"=>nil, "SERVER_PORT"=>8889, "HTTP_HOST"=>"localhost:8889", "rack.url_scheme"=>"chefzero", "rack.input"=>#<StringIO:0x00000001e1d448>}, @rest_base_prefix=["organizations", "chef"]>
DEBUG:
DEBUG: #<ChefZero::RestErrorResponse: ChefZero::RestErrorResponse>
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/rest_base.rb:81:in `rescue in get_data'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/rest_base.rb:73:in `get_data'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/endpoints/rest_object_endpoint.rb:18:in `get'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/rest_base.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/rest_router.rb:24:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/server.rb:641:in `block in app'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/server.rb:321:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/server.rb:321:in `handle_socketless_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.5.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:277:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:308:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:306:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:306:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:271:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:143:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:110:in `get'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/data_bag_item.rb:155:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item_keys.rb:116:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item.rb:73:in `load_keys'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item.rb:268:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef/knife/vault_create.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
/bin/knife:50:in `load'
/bin/knife:50:in `<main>'
DEBUG:
--- RESPONSE (404) ---
{"error":["Object not found: chefzero://localhost:8889/data/passwords/root_keys"]}
--- END RESPONSE ---
```

**Comment by rpattcorner** [comment]
The problem does seem to be related to there being inadequate configuration, but unclear how to do so in zero for vault.  Creating a client using knife doesn't help (but it does create a key).  Creating a node using knife doesn't help either (and why would we need to, give that there's a nodes directory in the repo path).  

In a scenario with no admins specified (no -A admin) the error shifts to /vault_admins.rb:32 where it becomes clear that the admin array falis to be located in Chef::Config

'''admin_array = [Chef::Config[:node_name]]'''

**Comment by mrmarbury** [comment]
@rpattcorner : did you solve this? And how? I currently have the same problem. I am trying to upload a vault to chef-zero to test a cluster config with chef-provisioning.

**Comment by rpattcorner** [comment]
Nope, sadly time did not permit and I moved on.  You'd think this would be easy, but not so much.

**Comment by bogklug** [comment]
This worked for me:
```
knife client create cli1 --local-mode --disable-editing >cli1.pem
knife vault create example_vault example_item '{"a":"b"}' --mode solo --local-mode --key cli1.pem --user 'cli1'
```

**Comment by snehaldwivedi** [comment]
@rpattcorner I have tested on the latest chef version and some of the other versions too and I am able to create vault without any issue as follows

`$ sudo knife vault create cred database -A snehal_d -S "cli-uban" -J abc.json`

```
$ knife vault list 
foo
passwords
cred
test1
```

I am closing the ticket for now , please reopen it if you still face some issue.
