### ISSUE TITLE
gem_source = nil ?

### ISSUE THREAD

**Issue by stenio123** [chef/chef-vault#213]
Hello

When I include this recipe in my cookbook I am getting the error undefined method `[]' for nil:NilClass

I believe this is because on gem installation, chef-vault cookbook expects the attirbute gem_source to provide the source of the gem.

However I don't want to host this gem in my servers, just want to rely on ruby gems installation.

Thoughts on how to resolve this?

**Comment by thommay** [comment]
Closing this since it looks like an issue with the cookbook rather than the gem. I'll look into how the cookbook is installing the gem soon.
