### ISSUE TITLE
knife vault in chefDK 0.15.16 cant see 'local/solo' vaults after initially creating them in MacOS 10.9.5

### ISSUE THREAD

**Issue by 8bitbrad** [chef/chef-vault#217]
how to reproduce on MacOS 10.9.5
- install chefDK 0.15.16
- create a fresh test cookbook: `chef generate cookbook vault_test`
- make sure data bag path is in knife.rb: `data_bag_path ["data_bags"]`
- mkdir data_bags in the test cookbook dir: `mkdir data_bags`
- create a vault: `knife vault create secret_vault secret_item`
   add a valid json item: "secret_one": "this is a secret" and save the vault
- attempt to show the vault: `knife vault show secret_vault secret_item -Fjson`
  this will result in: `ERROR: ChefVault::Exceptions::KeysNotFound: secret_vault/secret_item_keys could not be found`
-  are the vault files actually present?: `ls -lah data_bags/secret_vault/`
  Yes: 
  `-rw-r--r--  1 user  group   228B Jul 18 14:34 secret_item.json`
  `-rw-r--r--  1 user  group   481B Jul 18 14:34 secret_item_keys.json`

uninstalling chefDK and re-installing version 0.14.25 results in working local vaults

**Comment by 8bitbrad** [comment]
This is still an issue, on every chefDK release since 0.14.25.  I can replicate the issue on MacOS and Windows.  Am I doing something wrong that should never have worked in the firstplace?

**Comment by sanga1794** [comment]
HI @8bitbrad, I have tested it on the latest version and its working fine. Can you please check with the latest version.
```
ChefDK version: 4.12.0
Chef Infra Client version: 15.14.0
Chef InSpec version: 4.23.11
Test Kitchen version: 2.7.2
Foodcritic version: 16.3.0
Cookstyle version: 5.23.0
```
For time being we are closing this issue, add comment if you have any queries
