### ISSUE TITLE
Unable to override `:client_key_path` in ChefVault::Item.load

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef/chef-vault#221]
If a user follows [this section](https://github.com/chef/chef-vault/blob/master/README.md#specifying-an-alternate-node-name-or-client-key-path) in the README.md and provides `:client_key_path` to `ChefVault::Item.load` it gets overwritten by the default `Chef::Config[:client_key]`

This can be reproduced with the following:

```
require 'chef-vault'

foo = ChefVault::Item.load(
  'my_data_bag',
  'my_item',
  node_name: 'foo',
  client_key_path: '/path/to/client.pem'
)
```

Which produces the error:

```
[2016-08-11T14:58:43-04:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/chef/client.pem>
```

**Comment by thommay** [comment]
I think what you're seeing is that we've not got a properly set up `Chef::Config` context. The `:client_key_path` you pass to `ChefVault::Item.load` is solely for decrypting the symmetric key to the vault, and not for use by the http subsystem.

If you run this code in a recipe context, does the correct key get used?

**Comment by jerryaldrichiii** [comment]
Closing this due to age...it was likely me being dumb :smile:
