### ISSUE TITLE
knife vault download assumptions

### ISSUE THREAD

**Issue by rneu31** [chef/chef-vault#239]
If I'm reading the code properly, chef vault download does not write the contents of a data bag unless the data bag's information is stored as a specific key, `file-content`. Is this correct?

Below code merged with #104.
    
    if vault && item && path
      vault_item = ChefVault::Item.load(vault, item)
      File.open(path, "w") do |file|
        file.write(vault_item["file-content"])
      end

More of a question than an issue I suppose. Thanks.

**Comment by thommay** [comment]
Yeah, looks that way. I'm not really sure what the use case for `download` is (versus just `knife vault show -Fj foo bar > bar.json`), so if you had one, I'd be interested.

**Comment by rneu31** [comment]
Because I'm new-ish to this stuff and saw vault download before your suggestion. There's no real use case for it. Thanks.

While it's convenient.. is this possible or am I just crazy? I am brainstorming some system where users (admins) would create encrypted databags on their local PCs, check the encrypted data into git, and have the CI system push the encrypted content just as if it was never encrypted. I am trying to come up with a system where changes to data bags are seen by the CI system so it can act accordingly.
