### ISSUE TITLE
Kitchen test fallback

### ISSUE THREAD

**Issue by danhiris** [chef/chef-vault#247]
When I run a kitchen test and I have a vault in my data_bags, it doesn't fall back to the un-encrypted data bag, it just complains for not having the right client.pem to decrypt it.

To overcome this, I have to replace my encrypted vault file with an unencrypted file by the same name in the data_bags directory.

However, that will now be different than the data bag on the server, which is still a vault so it's not a true fall back.

Shouldn't the fallback be coded so that it checks for an un-encrypted file locally if it can't read the vault file due to this exception?

         ChefVault::Exceptions::SecretDecryption
         ---------------------------------------
         test_vault/testuser is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/chef-vault/libraries/helpers.rb:37:in `chef_vault_item'

          36:      if ChefVault::Item.vault?(bag, id)
          37>>       ChefVault::Item.load(bag, id)
          38:      elsif node['chef-vault']['databag_fallback']

**Comment by rneu31** [comment]
Have you tried using `chef_vault_item(bag, id)` instead of `ChefVault::Item.load(bag, id)`?

**Comment by karmakaze** [comment]
There are hints on lines 36 and 38. In test kitchen,
first it's expected *not* to look like a vault, so there should be data bag <name> but <name>_keys
second you should set node['chef-vault']['databag_fallback'] = true in your .kitchen.yml
```
  attributes:
    chef-vault:
      databag_fallback: true
```

**Comment by kamaradclimber** [comment]
It seems this issue has been solved by @karmakaze's answer. Thanks!
