### ISSUE TITLE
No man page for `knife help vault`

### ISSUE THREAD

**Issue by ricksebak** [chef/chef-vault#251]
All the knife subcommands for knife have a man page, such as `knife help cookbook` or `knife help role`. The vault subcommand is missing a similar man page.

```
knife help vault
ERROR: No help found for 'vault'
```

**Comment by iennae** [comment]
Hi,

Chef-vault is a plugin, while cookbook and role are part of knife. If you check out the information around creating custom plugins https://docs.chef.io/plugin_knife_custom.html you'll notice that what's required is the banner method. 

While there is not a specific knife vault help, there is a knife vault SUBCOMMAND help. If you do knife vault help you'll see the set of SUBCOMMANDS

<details>
** VAULT COMMANDS **
knife vault create VAULT ITEM VALUES (options)
knife vault delete VAULT ITEM (options)
knife vault download VAULT ITEM PATH (options)
knife vault edit VAULT ITEM (options)
knife vault isvault VAULT ITEM (options)
knife vault itemtype VAULT ITEM (options)
knife vault list (options)
knife vault refresh VAULT ITEM
knife vault remove VAULT ITEM VALUES (options)
knife vault rotate all keys
knife vault rotate keys VAULT ITEM (options)
knife vault show VAULT [ITEM] [VALUES] (options)
knife vault update VAULT ITEM VALUES (options)
</details>

For each of the subcommands there is help:
<details>
➜  chef-vault git:(master) knife vault create help
USAGE: knife vault create VAULT ITEM VALUES (options)
    -A, --admins ADMINS              Chef users to be added as admins
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    API Client Key
    -C, --clients CLIENTS            Chef clients to be added as clients
        --[no-]color                 Use colored output, defaults to enabled
    -c, --config CONFIG              The configuration file to use
        --config-option OPTION=VALUE Override a single configuration option
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
        --file FILE                  File to be added to vault item as file-content
        --[no-]fips                  Enable fips mode
    -F, --format FORMAT              Which format to use for output
    -J, --json FILE                  File containing JSON data to encrypt
    -K, --keys-mode KEYS_MODE        Mode in which to save vault keys
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
        --print-after                Show the data after a destructive operation
    -S, --search SEARCH              Chef SOLR search for clients
    -M, --mode MODE                  Chef mode to run in default - solo
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message
</details>

Hopefully this answers your question. If you want to improve how it works now, pull requests are welcome.
