### ISSUE TITLE
Changelog entry for 2.9.1

### ISSUE THREAD

**Issue by phene** [chef/chef-vault#262]
I see a version 2.9.1 has been released to rubygems, but there's no changelog or evidence of a 2.9.1 version bump in this repository: only a tag.

**Comment by iennae** [comment]
It was a minor release with only a bump in the github_changelog_generator gem. Version 3.0.0 went out yesterday and it is a more substantial release. Hopefully this answers your question. If not, please reopen with further information about your question.
