### ISSUE TITLE
Versions Released to Rubygems Before Changelog Entry is Written

### ISSUE THREAD

**Issue by phene** [chef/chef-vault#276]
There have been 2 releases of the gem without any update to the change log.

**Comment by phene** [comment]
Ok, now there's a release 3.2.0 gem and no entry in the changelog. Can you guys stop releasing new versions to rubygems before they are ready?

**Comment by kamaradclimber** [comment]
Yes indeed there was an "accidental" release of 3.2.0 using code supposed to do prerelease. Sorry for the inconvenience.

**Comment by kamaradclimber** [comment]
Changelog updated
