### ISSUE TITLE
/var/log/opscode/erchef/crash.log fullfilled with 404

### ISSUE THREAD

**Issue by 8la** [chef/chef-vault#283]
Hi!

We have detected that each time we load a vault item (we use ssl-vault) on the `/var/log/opscode/erchef/crash.log` appears lines like: 

```code
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
{<<"method=GET; path=/organizations/<myorg>/data/ssl-vault/my_item_name_key_node.fqdn.name; status=404; ">>,"Not Found"}
```

Debugging with chef-shell whe have detected that the lines appears when ChefVault::Item.secret [1] method is invoked whe you load a vault item with:  ChefVault::Item.load

Seems like if chef-vault was looking for more presedence key for that vault item for that host other tan the public node key one.

[1] - https://github.com/chef/chef-vault/blob/master/lib/chef-vault/item.rb#L155

**Comment by thommay** [comment]
This looks as though it should be fixed by #280, which will be released shortly.
