### ISSUE TITLE
With recreated nodes, existing keys are not updated

### ISSUE THREAD

**Issue by krzkowalczyk** [chef/chef-vault#286]
With a new chef-vault version 3.1.0 a new feature was introduced:
- Avoid re-encrypting key for all existing clients [\#269](https://github.com/chef/chef-vault/pull/269)

This change is undesirable in environments where nodes are recreated. In such situations re-encrypting keys was fixing obsolete keys and allowing access to vault's items. Now it does not update client keys, and requires to delete, and re-add client to vault, for all vault items.

Keys should be re-encrypted if node client key has changed, or there should be an opt-in flag to force re-encryption.

**Comment by kamaradclimber** [comment]
Looking at how the code is written, a short term workaround would be to rotate the symetrical key with `knife vault rotate all keys`.
I'll have a quick look at how adding an option to force re-encryption on a normal refresh.
