### ISSUE TITLE
Vault throws exception when running in solo mode and not connected to network

### ISSUE THREAD

**Issue by nathan-lochala** [chef/chef-vault#288]
According to the documentation, solo mode foregoes the need to connect to a chef server and instead uses json files stored locally in the cookbook repo for the source of encrypted items and keys. 
_IE: data_bags/vault/secrets.json and secrets_keys.json._ 

That is not the case for me. If I'm disconnected from the network and I run :
`knife vault show vault secrets --mode solo`

I receive an error:
`ERROR: Error connecting to https://chef.xxxxxxx.edu/organizations/ts/data/vault/secrets_keys, retry 1/5`

**I am running on the following versions:**
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
Chef: 12.19.36
chef-vault 2.9.1

**Comment by kamaradclimber** [comment]
Sorry for long delay before answering this one.

I can reproduce this issue with 2.9.1 but not with chef-vault 3.3.0.

Are you able to upgrade chef-vault?

**Comment by snehaldwivedi** [comment]
I have tested it on both the versions and its working fine. Can you please check with the latest version.

```
Chef Development Kit Version: 1.3.43
chef-client version: 16.1.16
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
```

```
> knife vault show foo10 -M solo
bar10
```

```
> chef -v
ChefDK version: 4.8.23
Chef Infra Client version: 15.11.8
Chef InSpec version: 4.19.0
Test Kitchen version: 2.5.1
Foodcritic version: 16.2.0
Cookstyle version: 5.23.0
```

```
> knife vault show foo11 -M solo
bar11
```
