### ISSUE TITLE
Cannot remove node from vault client list.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [chef/chef-vault#290]
I'm getting an error when attempting to remove a client entry from my vault.  **The key to note here** is that the node was deleted from the console _before_ I attempted to remove the node from the client list of the vault in question.  Therefore, it seems I'm stuck with a stale entry in my client list for my vault without any way to remove it.

COMMAND:
`knife vault remove my_vault my_vault_item -C myserver.domain.com`

ERROR:
`WARN: node 'myserver.domain.com' has no private key; skipping`

Is there a way to forcefully remove an entry if the node has been removed from the server?  There should be a way to do this with a --force switch to the knife vault command if there is no way around this.

**Comment by kamaradclimber** [comment]
I'll have a look

**Comment by kamaradclimber** [comment]
I can't reproduce your issue with chef-vault 3.3.0.
I've tried to add a non existing client A in the secret_keys.json and tried to delete it with knife vault remove with success.
If I try to remove a client B that is not mentioned in secret_keys.json (and if I still have the non existing client A), the command display the warning you give but completes successfully (having removed nothing from the secret_keys.json as expected).

The output you give is a warning and should not trigger an error.

Could you:
- give the version of chef-vault you are using (with chef version if possible)
- run the same command with `-VV` and give the outcome
- give the exit code of your command `knife vault remove my_vault my_vault_item -C myserver.domain.com`

Thanks

**Comment by snehaldwivedi** [comment]
I have tested this on latest versions and some versions till `chef-vault (3.1.0)` its working fine. Can you try the latest version.
