### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by royaldark** [chef/chef-vault#293]
[This section](https://github.com/chef/chef-vault#the-future-of-chef-vault) of the Readme refers to chef-vault v3 in the future tense. Since v3 has been out for some time, it would be nice if this section were updated with more relevant information about the changes (breaking, especially) in v3 (the changelog is not very helpful in that regard).

Is the KMS plugin available? Which plugins exist currently?

**Comment by kamaradclimber** [comment]
@royaldark you're right, v3 was not released with the documented improvements.

As far as I know, there is no master plan for chef-vault future. New features and PR are of course looked at, but there is no decided roadmap.
I've submitted a PR to remove the outdated section from readme.
