### ISSUE TITLE
When creating a vault from workstation, it does not recognize the private key of node.

### ISSUE THREAD

**Issue by priyanshuagrawalchef** [chef/chef-vault#295]
When creating a vault from workstation, 

 knife vault create VAULTNAME VAULTITEM -A USER1,USER2' -M client -C 'nodename1,nodename2' -J ./xyzd.json
WARN: node 'nodename1' has no private key; skipping
WARN: node 'nodename2' has no private key; skipping

Though the private key is present on node.

**Comment by kamaradclimber** [comment]
You're right it is a wording issue since this message is printed when the public key is not found. I'll issue a patch.

**Comment by priyanshuagrawalchef** [comment]
How should I get rid of this issue??
