### ISSUE TITLE
ERROR: ChefVault::Exceptions::SecretDecryption: keys/edh-preprod_chefadmin_keytab is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef/chef-vault#297]
Hi am trying to stand up a new chef server on an ec2 instance and I downloaded all data_bags; roles; cookbooks; environments from my working OnPrem chef-server and uploaded them to my new chef-server which is on ec2 instance. But when am running below knife bootstrap command am facing the exception with ChefVault. So here as below there is a data_bag named as keys and there are some items in it in which type of this item edh-preprod_chefadmin_keytab is vault. I haven't created any vault with name keys. Could any please help me to resolve this issue.
[root@aachef01 .chef]# knife bootstrap *.*.*.* -N aatest02 -x ec2-user -i /home/xxx/xxx.pem --sudo -s --server-url https://aachef01.domain.com/organizations/dev -r 'role[base_adjoined]' --bootstrap-vault-json '{"keys":["edh-preprod_chefadmin_keytab"],"preprod_vault":["NIFI_keytab","deploy-keys","PORTAL","passwords","svc_hadoopbind","dmdbsdpp_write","dev.cloud.domain.key"]}' -E edh-preprod-aws -y
Creating new client for aatest02
Creating new node for aatest02
ERROR: ChefVault::Exceptions::SecretDecryption: keys/edh-preprod_chefadmin_keytab is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

[root@aachef01 keys]# ll
total 368
-rw-r----- 1 root root   2004 Dec  6 19:41 edh-preprod_chefadmin_keytab.json
-rw-r----- 1 root root 98450 Dec  6 21:52 edh-preprod_chefadmin_keytab_keys.json
-rw-r----- 1 root root 2001 Dec  6 19:41 edh-prod_chefadmin_keytab.json
-rw-r----- 1 root root 164324 Dec  6 19:41 edh-prod_chefadmin_keytab_keys.json
-rw-r----- 1 root root 96576 Dec  6 19:41 edh-prod_nagadmin_auth_keys.json
[root@aachef01 keys]# pwd
/var/chef/data_bags/keys
[root@aachef01 keys]# knife vault list
preprod_vault
production_vault

**Comment by SrikarshVardhanreddyKolanu** [comment]
Closing it as I resolved this with a secret

**Comment by ejiec004** [comment]
> Closing it as I resolved this with a secret

Hey Kolanu, can you describe little more about the resolution, I am getting the same error.

**Comment by elibroftw** [comment]
Leaving this here for people who want an answer on what to do if they encounter the could not decrypt error.
```
knife data bag delete VAULT ITEM_keys [--user=USER]
knife data bag delete VAULT ITEM [--user=USER]
```
