### ISSUE TITLE
List admin/clients in vault

### ISSUE THREAD

**Issue by badsector3** [chef/chef-vault#302]
Hi. 

    Is there a way to list admins and clients assigned to vault? I couldn't find.

**Comment by kamaradclimber** [comment]
Hello @badsector3 ,

as far as I know there is no command to list admins or clients for a given vault item.
However the json structure is quite simple and exposes that information.

Using vault item `my_secret` from vault `secrets`, you can use jq to see the list of clients:
`cat data_bags/secrets/my_secret_keys.json | jq .clients`

If you are working in chef code, you can simply load the data bag item (not the secret) instead.

I hope this help you.
