### ISSUE TITLE
How do I resolve the issue with decryption of encrypted data bag item

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef/chef-vault#307]
I uploaded a data bag item using vault then started bootstrap 

`knife bootstrap ipaddress -N nodename -x ec2-user -i file.pem --sudo --server-url https://chefserver/organizations/org -r 'role[basexxx]' -E environmentxxx -y`

for one client. Then it showed error 

`[Databag]/[Databag Item] is not encrypted with your public key. Contact an administrator of the vault item to encrypt for you!`

So I added the client01 to the vault using 

`knife vault update DATABAG DATABAGITEM -J File.json -S "role:base" -M "client" -C "client01" -A "admin"`

and now when I ran bootstrap it's showing the below error

`[Databag]/[Databag Item] is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')
`

Even tried `knife vault refresh Databag Databag Item`

Can anyone suggest how to resolve this

**Comment by SrikarshVardhanreddyKolanu** [comment]
@admins Anyone looking over this?

**Comment by kamaradclimber** [comment]
Could you post:
- chef-vault + chef gems version you are using
- the output of the same commands with `-VV`
- the content of DATABAGITEM.json and DATABAGITEM_keys.json (don't worry I won't be able to read your secret)

**Comment by wainerthemainer** [comment]
I am having the same issue, I have an existing chef-vault and when I add new machines to it with the below command:
`knife vault update master_vault env_creds -A "account1,account2,machine1,machine2" -J ..\cookbooks\data_bags\master_vault \env_creds.json -M client`

And I even see the new machine names in the vault itself through Chef Manage, and yet every time I try to run it on these new machines I get:
> [2018-07-24T10:27:00-04:00] FATAL: ChefVault::Exceptions::SecretDecryption: master_vault/env_creds is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')

When I try the 'knife vault refresh':
`knife vault refresh master_vault env_creds`

I get the below error:
> ERROR: The data in your request was invalid.  Response: invalid search query: '[]'

Any ideas, I've looked all over google and have had no luck.

**Comment by josephmilla** [comment]
@wainerthemainer I think `-A` is meant to be used for (admin) accounts not clients.

**Comment by neaGaze** [comment]
Even I'm getting this issue with v3.1.1. Is this issue resolved already? If not, it needs to be fixed asap

**Comment by neaGaze** [comment]
Found a solution to the issue. While running `knife bootstrap` command inserting an additional param `--bootstrap-vault-json '{"<data_bag_name>":["<data_bag_item_name>"]}'` did the trick for me. I'm kind of disappointed that there doesn't seem to be enough documentation around this.

**Comment by dheerajd-msys** [comment]
Hi @SrikarshVardhanreddyKolanu 
Could you please confirm if the solution provided [here](https://github.com/chef/chef-vault/issues/307#issuecomment-507809011) works for you too?

@neaGaze Documentation for parameter `--bootstrap-vault-json` https://github.com/chef/chef-workstation/blob/master/www/content/workstation/knife_bootstrap.md#chef-vault-options. 

Thanks,
Dheeraj

**Comment by dheerajd-msys** [comment]
Hi @SrikarshVardhanreddyKolanu Please check above comments. Closing this issue for now per https://github.com/chef/chef-vault/issues/307#issuecomment-644044863

Thanks,
Dheeraj
