### ISSUE TITLE
Keys mode undocumented at all

### ISSUE THREAD

**Issue by jsirex** [chef/chef-vault#309]
Help says:
"    -K, --keys-mode KEYS_MODE        Mode in which to save vault keys"
What is the "KEYS_MODE"?  Which values are possible? 
Do you have any use cases? Could you please improve help?

**Comment by thommay** [comment]
Thanks for the bug report. Yes, we should improve the help. In summary, the mode is either `default`, which saves all the copies of the client encrypted symmettric key into a single `item_keys` data bag item, or `sparse`, which creates a new data bag item per client. Sparse helps performance a lot for *really* large (greater than a thousand clients) vault usage.

**Comment by josephmilla** [comment]
@thommay to be honest, why not just use sparse mode as the default?

**Comment by sanga1794** [comment]
PR https://github.com/chef/chef-vault/pull/325 got merged.
