### ISSUE TITLE
ERROR: Chef::Exceptions::InvalidDataBagPath: Data bag path '/home/josh/chef-repo/data_bags' is invalid

### ISSUE THREAD

**Issue by joshk132** [chef/chef-vault#321]
I am trying to create a chef vault that will hold a username and password but it will not create one that will seem to work. I see in chef manage that the databag is created as well as that it has a username and password field so my JSON is working correctly. 

**Error message:**

` ERROR: Chef::Exceptions::InvalidDataBagPath: Data bag path '/home/josh/chef-repo/data_bags' is invalid`

**Command to create vault:**

`sudo knife vault create git_personal <vault_password> -A "josh" -M client -J ./git_personal.json`

I am just installed chef dk about a month ago using the latest at the time. This is the first time I have tried to create a chef vault and so far just failure. I do have the chef-vault gem installed already with the latest version as of Sept 10 2018

Anyone know what might be going on?

**Comment by koldrid** [comment]
-m client not -M client

**Comment by yamlCase** [comment]
I ran into this too, the blog entry I'm following has `-M` instead of `-m`:
https://blog.chef.io/2016/01/21/chef-vault-what-is-it-and-what-can-it-do-for-you/

**Comment by arielrolfo** [comment]
"-M [mode]" is fine

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/12053180/77833925-a4bd0f80-711f-11ea-9de5-fbdfbbf564f7.png">
