### ISSUE TITLE
knife vault on windows 10 fails due to ERROR: Chef::Exceptions::InvalidDataBagPath

### ISSUE THREAD

**Issue by nmat** [chef/chef-vault#333]
# Description
On windows 10 `knife vault list` gives InvalidDataBagPath is invalid everytime from powershell. Also tested to make a vault entry using `knife vault create` and same problem occurs.

In output it tries to find '$PATH\data_bags' in the end which does not seem to exist. 

This error could be better explained to be: data bag does not exist or something or ask to create the folder if it does not exist.

If I create the directory manually it fixes the error but its not obvious according to error that just says: is invalid 

# ChefDK Version

Chef Development Kit Version: 3.1.1

# Platform Version

windows 10

**Comment by tyler-ball** [comment]
Moved this here from ChefDK. Thanks for the report @nmat!
