### ISSUE TITLE
rotate keys with --clean-unknown-clients also cleans known clients

### ISSUE THREAD

**Issue by jstange** [chef/chef-vault#334]
# Version:

3.4.3

# Environment:

Chef Server 12.17.15 with client 14.14.29, on various releases of CentOS and RHEL

# Steps to Reproduce:

1. Pick a vault with one or more existing clients (nodes/clients which definitely still exist in Chef), and a `search_query` that has only a subset of those, or none of them at all.
2. Inspect `clients` and `search_query` visually with `knife data bag show foo bar_keys`
3. `knife vault rotate keys foo bar --clean-unknown-clients`
4. Inspect `clients` and `search_query` again; all clients which are not currently matched by `search_query` will be gone, including those which still exist in Chef.

# Expected Result:

According to the docs at https://github.com/chef/chef-vault/blob/master/KNIFE_EXAMPLES.md#rotate-all-keys:

`remove clients which have been deleted from Chef but not from the vault`

# Actual Result:

All clients are removed.

It's plausible that this could be intended behavior, but if so, then the documentation is misleading and should be corrected.

Here's the code that does the thing:

```
    def remove_unknown_nodes
      # build a list of clients to remove so we don't
      # mutate the clients while iterating over search results
      clients_to_remove = []
      get_clients.each do |nodename|
        clients_to_remove.push(nodename) unless node_exists?(nodename)
      end
      # now delete any flagged clients from the keys data bag
      clients_to_remove.each do |client|
        ChefVault::Log.warn "Removing unknown client '#{client}'"
        keys.delete(load_actor(client, "clients"))
      end
    end

    # checks if a node exists on the Chef server by performing
    # a search against the node index.  If the search returns no
    # results, the node does not exist.
    # @param nodename [String] the name of the node
    # @return [Boolean] whether the node exists or not
    def node_exists?(nodename)
      search_results.include?(nodename)
    end

```

`node_exists?`, seems to treat the vault's current `search_results` as a cache, but this assumes that the current query covers an exhaustive list of nodes that should have access. For our users' workflows, where they sometimes grant access to a node at a time with `knife vault update foo bar --search name:MYNODE`, this is not the case.

There's a `client_exists?` method directly below that one, which looks like it would do the correct thing, running `Chef::ApiClient.load(clientname)`. I could see that being painfully slow for long lists of nodes, so perhaps a query that could ask for the nodes in a batch? I'm not familiar enough with the Chef API to know whether that's a thing.

**Comment by snehaldwivedi** [comment]
@jstange Can you please check with latest version as it is working fine from our end.

**Platform:** Ubuntu 18.04.4
**Chef:** 12.14.60

Following the steps, I have tried
1. I have created the vault with 6 node\clients in it
```
$ knife data bag show -F json foo bar_keys
WARNING: Unencrypted data bag detected, ignoring any provided secret options.
{
  "id": "bar_keys",
  "admins": [
    "chefadmin",
    "pivotal",
    "snehal_d"
  ],
  "clients": [
    "node-learn_chef_apache2",
    "node-git",
    "node-push-job",
    "node2.test",
    "node1",
    "node-win"
  ],
  "search_query": "*:*",
  "mode": "default",
  "node-learn_chef_apache2": "",
  "node-git": "",
  "node-push-job": "",
  "node2.test": "",
  "chefadmin": "",
  "pivotal": "",
  "snehal_d": "",
  "node1": "",
  "node-win": ""
}
```

2. Removed `node-win` form the chef and only that particular node was removed

```
$ knife node delete node-win
Do you really want to delete node-win? (Y/N) Y
Deleted node[node-win]
```

```
$ knife vault rotate_keys foo bar -M client --clean-unknown-clients
WARN: Removing unknown client 'node-win'

```
```
$ knife data bag show -F json foo bar_keys
WARNING: Unencrypted data bag detected, ignoring any provided secret options.
{
  "id": "bar_keys",
  "admins": [
    "chefadmin",
    "pivotal",
    "snehal_d"
  ],
  "clients": [
    "node-learn_chef_apache2",
    "node-git",
    "node-push-job",
    "node2.test",
    "node1"
  ],
  "search_query": "*:*",
  "mode": "default",
  "node-learn_chef_apache2": "",
  "node-git": "",
  "node-push-job": "",
  "node2.test": "",
  "chefadmin": "",
  "pivotal": "",
  "snehal_d": "",
  "node1": "",
}
```

3. Repeated **step 2** with `node1` and only that was removed from the vault

```
$ knife data bag show -F json foo bar_keys
WARNING: Unencrypted data bag detected, ignoring any provided secret options.
{
  "id": "bar_keys",
  "admins": [
    "chefadmin",
    "pivotal",
    "snehal_d"
  ],
  "clients": [
    "node-learn_chef_apache2",
    "node-git",
    "node-push-job",
    "node2.test"
  ],
  "search_query": "*:*",
  "mode": "default",
  "node-learn_chef_apache2": "",
  "node-git": "",
  "node-push-job": "",
  "node2.test": "",
  "chefadmin": "",
  "pivotal": "",
  "snehal_d": ""
}
```

**Comment by snehaldwivedi** [comment]
Hi @jstange , for time being we are closing this issue, add comment if you have any queries
