### ISSUE TITLE
Syntax errors in vault_admins.rb 

### ISSUE THREAD

**Issue by DrHappyAngry** [chef/chef-vault#358]
# Version:
4.0.10

# Environment:
Ubuntu 18.04

# Scenario:
knife ssl fetch fails with syntax errors, some other commands fail that rely on the vault

# Steps to Reproduce:
update gem to 4.0.10

# Expected Result:
knife ssl fetch and other vault commands work

# Actual Result:
STDERR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-vault-4.0.10/lib/chef/knife/vault_update.rb:17:in `require_relative': /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-vault-4.0.10/lib/chef/knife/vault_admins.rb:31: syntax error, unexpected keyword_end (SyntaxError)
+       end
        ^~~
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-vault-4.0.10/lib/chef/knife/vault_admins.rb:43: syntax error, unexpected end-of-input, expecting keyword_end
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-vault-4.0.10/lib/chef/knife/vault_update.rb:17:in `<top (required)>'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife.rb:152:in `subcommand_class_from'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/knife.rb:215:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/lib/chef/application/knife.rb:161:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.9.13/bin/knife:24:in `<top (required)>'
	from /usr/bin/knife:74:in `load'
	from /usr/bin/knife:74:in `<main>'

Lines 30 and 31 in vault_admins.rb have additional + signs at the start of the lines, removing them fixes the issue
https://github.com/chef/chef-vault/blob/3c739c307530f57d6b372fb999daebba2f5e263c/lib/chef/knife/vault_admins.rb#L30-L31

**Comment by sanga1794** [comment]
Fixed in https://github.com/chef/chef-vault/pull/359.
