### ISSUE TITLE
chef-vault command not returning any results

### ISSUE THREAD

**Issue by joejoe19** [chef/chef-vault#373]
# Version:

4.1.0

# Environment:

RHEL 7.9

# Scenario:

I'm trying to pull a credential from the vault using the chef-vault command but no results are returned.

# Steps to Reproduce:

I am able to use the knife command to access the value successfully... 
> knife vault show test_vault dbcredz password -c /etc/chef/client.rb
id:       dbcredz
password: thisisthepassword

However, using the equivalent chef-vault command nothing is returned... 
> chef-vault -k /etc/chef/client.rb -v test_vault -i dbcredz -a password

# Expected Result:

I expect thisisthepassword to be returned by the chef-vault command as it is by the knife command.

# Actual Result:

If I change/misspell the vault or the item an error is thrown that states... test_vaul/dbcredz_keys could not be found (ChefVault::Exceptions::KeysNotFound)

**Comment by nikhil2611** [comment]
Hi @joejoe19 , I just need to confirm that how you created the `test_vault` vault here. Can you share the command and also the config set  in the  `client.rb` file if possible
