### ISSUE TITLE
Gemspec gives incorrect Ruby version being supported with "rescue in blocks" syntax being used

### ISSUE THREAD

**Issue by ky4n** [chef/chef-vault#378]
# Version:

chef-vault gem: 4.1.0 and 4.1.3
chef-vault Chef cookbook: 3.1.0
Chef embedded ruby: ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]

# Environment:

Ubuntu 16

# Scenario:

Today new version of the chef-vault gem was released, which is used by chef-vault cookbook under the hood. Despite the versions being old, there was no version pinning for chef-vault gem in chef-vault cookbook nor the chef-vault gem's gemspec didn't indicate the proper Ruby version being supported supported.

As per gemspec, chef-vault gem is compatible with Ruby 2.4+, but [this commit](https://github.com/chef/chef-vault/pull/377/commits/bd0bd4d313c76aa9408c2fc416125bdcd47450b3) has introduced Ruby syntax that was added in Ruby 2.5.9 (`rescue` in blocks) so for any previous Ruby versions it breaks with a stacktrace (only top of the trace provided, the rest doesn't seem to be relevant):
```
SyntaxError: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-4.1.3/lib/chef-vault/item.rb:95: syntax error, unexpected keyword_rescue, expecting keyword_end
        rescue ChefVault::Exceptions::Client
              ^
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-4.1.3/lib/chef-vault/item.rb:484: syntax error, unexpected keyword_end, expecting end-of-input
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-4.1.3/lib/chef-vault.rb:28:in `require_relative'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-4.1.3/lib/chef-vault.rb:28:in `<top (required)>'
/opt/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `require'
/opt/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/opt/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:34:in `require'
```

# Steps to Reproduce:

Run Chef client with Ruby version 2.4.5 with `chef-vault` cookbook included in version 3.1.0

# Expected Result:

Chef-client using chef-vault cookbook to pass without exceptions being thrown and incompatible code not being installed on old Ruby versions.

# Actual Result:

Chef-client run fails with the exception and stack trace provided above despite everything seemingly being compatible.

**Comment by pkatiushyn** [comment]
+1 same issue.

**Comment by ky4n** [comment]
As a workaround, we've locally updated the cookbook's metadata to pin gem version in cookbook's `metadata.json`: `"gems":[["chef-vault", "< 4.1.3"]]` (`metadata.json` is a single-line blob so I can't do a nice diff here).
