### ISSUE TITLE
"Item itemname_keys not found in data bag databagname", while I try to create a new vault with newer versions of Chef Workstation

### ISSUE THREAD

**Issue by grdz** [chef/chef-vault#381]
# Version:

chef-vault 4.1.0 but it is the same with chef-vault 4.1.4.

# Environment:

Fedora 34,
Chef Workstation version: 21.2.278
Chef Infra Client version: 16.10.8
Chef InSpec version: 4.26.4
Chef CLI version: 3.1.1
Chef Habitat version: 1.6.181
Test Kitchen version: 2.10.0
Cookstyle version: 7.8.0

# Scenario:

I want to create a new vault. While executing the command `knife vault create -VVV vault123 item123 '{"test": "test"}'` I got this error:

```
INFO: Using configuration from /home/my-username-censored/chef/.chef/knife.rb
Traceback (most recent call last):
	12: from /opt/chef-workstation/bin/knife:355:in `<main>'
	11: from /opt/chef-workstation/bin/knife:355:in `load'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/bin/knife:24:in `<top (required)>'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/application/knife.rb:165:in `run'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:229:in `run'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:489:in `run_with_pretty_exceptions'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:490:in `block in run_with_pretty_exceptions'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef/knife/vault_create.rb:71:in `run'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:291:in `load'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:79:in `load_keys'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:236:in `load'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/data_bag_item.rb:144:in `load': Item item123_keys not found in data bag vault123. Other items found:  (Chef::Exceptions::InvalidDataBagItemID)
	12: from /opt/chef-workstation/bin/knife:355:in `<main>'
	11: from /opt/chef-workstation/bin/knife:355:in `load'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/bin/knife:24:in `<top (required)>'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/application/knife.rb:165:in `run'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:229:in `run'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:489:in `run_with_pretty_exceptions'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/knife.rb:490:in `block in run_with_pretty_exceptions'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef/knife/vault_create.rb:71:in `run'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:291:in `load'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:79:in `load_keys'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:235:in `load'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:237:in `rescue in load': uninitialized constant Net::HTTPServerException (NameError)
```

# Steps to Reproduce:

Upgrading chef-vault gem to 4.1.4 didn't help, so just try to create a new vault using `knife vault create` command, while you have installed Chef Workstation 21.2.278 or newer. Upgrading Chef Workstation did not help either. Only downgrade to ChefDK 4.13.3 helped.

# Expected Result:

I expect the command `knife vault create` to work even in the latest Chef Workstation versions. It seems like there is some compatibility issue between the latest Chef Workstations and chef-vault gem, and I was not able to upgrade chef-vault to a version that would work.

# Actual Result:

The vault is not being created, data bag is not created. There is just an error that there is no `item_keys` item, while I expected that this item would be created by this command, so it's obvious that it does not exist yet during `knife vault create` command. The same thing was reproduced by my colleague, with the same versions of Chef Workstation and Chef Vault, but on a different operating system.

**Comment by MattoHopkins** [comment]
@grdz did you ever fix this? Running into the exact same issue. Running @nikhil2611's command failed as well (same error)

``/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.8/lib/chef/data_bag_item.rb:144:in `load': Item item123_keys not found in data bag vault123. Other items found:  (Chef::Exceptions::InvalidDataBagItemID)``

**Comment by grdz** [comment]
@MattoHopkins no, still no solution. But I am glad to hear that I am not alone, altough you're probably not happy :D I wonder what is the difference between our configuration and the one that @nikhil2611 have. What is the difference here, that this problem occurs for us, but not for nikhil.

**Comment by MattoHopkins** [comment]
@grdz actually did resolve this. had to add `knife[:vault_mode] = 'client'` into my knife.rb

**Comment by grdz** [comment]
@MattoHopkins thanks! I can confirm that this is working! I am closing the issue, since you resolved it.

**Comment by wzin** [comment]
> `knife[:vault_mode] = 'client'`

I had exactly the same problem and this solved it.

What's not OK is that I was running on a fresh config without any special modifications and vault would not work for me OOTB.

Thanks.
