### ISSUE TITLE
Add GPG key support

### ISSUE THREAD

**Issue by bobziuchkovski** [chef/chef-vault#65]
What about adding gpg support for public/private pairs using https://github.com/ueno/ruby-gpgme? This would potentially address https://github.com/Nordstrom/chef-vault/issues/58.

If I were to add GPG support and submit the patches as a PR, would you consider it for inclusion, or is GPG support something you would consider out-of-scope entirely?

**Comment by tas50** [comment]
This is very much something we would like to handle natively in Chef Infra Client, but at this point in time we don't plan to expand support to additional stores in the chef-vault project. I'm going to close this out since we won't be working this issue.
